### ISSUE TITLE
Merge into livepeerjs?

### ISSUE THREAD

**Issue by ericxtang** [adamsoffer/livepeer-subgraph#1]
Hi Adam,

Looks like there are some new activities here.  Do you think we should merge the changes into `livepeerjs`?

**Comment by adamsoffer** [comment]
Hey - yeah definitely that was the plan. Although, I _just now_ discovered an issue with one of the updates I made. The Subgraph wrongly assumes the protocol distributes network fees at the moment a transcoder calls reward, but that's only the case with reward tokens, so delegator fee shares are being indexed incorrectly. Opening up a separate issue for this...

**Comment by adamsoffer** [comment]
#2

**Comment by adamsoffer** [comment]
@ericxtang I've opened a PR on livepeerjs
